name: CI

on:
  push:
    branches:
      - main

jobs:
  verificar:
    name: Verificar servidor
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Verificar servidor
        run: |
          hostname
          pwd
          ls -la

  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar Deploy
        run: |
          echo "Iniciando deployment..."
          echo "Servidor: $(hostname)"
          echo "Directorio: $(pwd)"